name: CI pipeline

on:
  push:
    branches: [ "main", "release/*", "maintenance/*", "ci/*" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    secrets: {}
    outputs:
      hashes:
        description: "Hashes of the artifacts that were built"
        value: ${{ jobs.build.outputs.hashes }}
  workflow_dispatch: {}
permissions:
  actions: read
  contents: read
env:
  MAIN_PYTHON_VERSION: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.artifact-hashes.outputs.hashes }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
      - name: Install build tools
        run: pip install --upgrade build setuptools pip wheel swig                 
      - name: Build release artifacts
        run: python -m build
      - name: Record release artifact hashes
        id: artifact-hashes
        run: cd dist && echo "hashes=$(sha256sum * | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugin-dist
          path: dist/
  pytest-coverage:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: plugin-dist
          path: dist/
      - name: Install Python dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          WHEEL=(dist/*.whl)
          REQ="${WHEEL[0]}[testing]"
          python -m pip install $REQ        
