name: Static analysis

on: ["push", "pull_request"]

permissions:
  actions: read
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install --upgrade pip isort black
      - name: Check import order
        run: isort --profile black --line-length 80 --check moj_elektro_v1*
      - name: Run Black
        run: black -S --line-length 80 --check moj_elektro_v1*
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Run mypy
        run: mypy moj_elektro_v1
    
